/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2022-12-07 16:56:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import activityManagement.userModular.dao.UserDao;
import activityManagement.activityModular.dao.ActivityDao;
import activityManagement.activityModular.entity.Yuanwang;
import activityManagement.activityModular.entity.Activity;
import activityManagement.userModular.entity.User;
import activityManagement.userModular.dao.YuanwangDao;
import java.util.List;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import activityManagement.activityModular.entity.Defen;
import activityManagement.activityModular.dao.DefenDao;

public final class adminPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("activityManagement.activityModular.entity.Defen");
    _jspx_imports_classes.add("activityManagement.activityModular.dao.DefenDao");
    _jspx_imports_classes.add("activityManagement.userModular.dao.YuanwangDao");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("activityManagement.activityModular.entity.Activity");
    _jspx_imports_classes.add("activityManagement.activityModular.dao.ActivityDao");
    _jspx_imports_classes.add("activityManagement.userModular.entity.User");
    _jspx_imports_classes.add("java.text.DateFormat");
    _jspx_imports_classes.add("activityManagement.userModular.dao.UserDao");
    _jspx_imports_classes.add("activityManagement.activityModular.entity.Yuanwang");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<title>TOPY for Senior</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"layui/css/layui.css\">\n");
      out.write("\n");
      out.write("</head>\n");

	DateFormat df = new SimpleDateFormat("yyyy/MM/dd");

      out.write("\n");
      out.write("<body>\n");
      out.write("	<script src=\"layui/layui.js\"></script>\n");
      out.write("	<div class=\"layui-tab\">\n");
      out.write("		<ul class=\"layui-tab-title\">\n");
      out.write("			<li class=\"layui-this\">User management</li>\n");
      out.write("			<li>Event management</li>\n");
      out.write("			<li>Current activity</li>\n");
      out.write("			<li>Event release</li>\n");
      out.write("			<li>Wish list</li>\n");
      out.write("			<li>Evaluation list</li>\n");
      out.write("			<li class=\"layui-nav-item layui-layout-right\"><a\n");
      out.write("				href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginUser.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("-The administrator signs out</a></li>\n");
      out.write("		</ul>\n");
      out.write("		<div class=\"layui-tab-content\">\n");
      out.write("			<div class=\"layui-tab-item layui-show\">\n");
      out.write("\n");
      out.write("				<table class=\"layui-table\">\n");
      out.write("					<colgroup>\n");
      out.write("						<col width=\"150\">\n");
      out.write("						<col width=\"200\">\n");
      out.write("						<col>\n");
      out.write("					</colgroup>\n");
      out.write("					<thead>\n");
      out.write("						<tr>\n");
      out.write("							<th>serial number</th>\n");
      out.write("							<th>User name</th>\n");
      out.write("							<th>Name</th>\n");
      out.write("							<th>Sex</th>\n");
      out.write("							<th>Mobile phone number</th>\n");
      out.write("							<th>Date of registration</th>\n");
      out.write("							<th>revise</th>\n");
      out.write("							<th>Delete</th>\n");
      out.write("						</tr>\n");
      out.write("					</thead>\n");
      out.write("					<tbody>\n");
      out.write("						");

							UserDao userDao = new UserDao();
							List<User> userList = userDao.queryAllList();
							for (int i = 0; i < userList.size(); i++) {
								User user = userList.get(i);
						
      out.write("\n");
      out.write("						<tr>\n");
      out.write("							<td>");
      out.print(i + 1);
      out.write("</td>\n");
      out.write("							<td>");
      out.print(user.getUserName());
      out.write("</td>\n");
      out.write("							<td>");
      out.print(user.getNickname());
      out.write("</td>\n");
      out.write("							<td>\n");
      out.write("								");

									if (user.getSex() != null) {
								
      out.print(user.getSex().equals("M") ? "M" : "F");
      out.write(' ');

 	}
 
      out.write("\n");
      out.write("							</td>\n");
      out.write("\n");
      out.write("							<td>");
      out.print(user.getPhoneNum());
      out.write("</td>\n");
      out.write("							<td>\n");
      out.write("								");

									if (user.getRegisterDate() != null) {
								
      out.print(df.format(user.getRegisterDate()));
      out.write(' ');

 	}
 
      out.write("\n");
      out.write("							</td>\n");
      out.write("							<td><a\n");
      out.write("								href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/userEdit.jsp?userId=");
      out.print(user.getId() );
      out.write("\"\n");
      out.write("								class=\"layui-btn layui-btn-sm layui-btn-radius\">revise</a>\n");
      out.write("							<td><a\n");
      out.write("								href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/deletUser?userId=");
      out.print(user.getId() );
      out.write("\"\n");
      out.write("								class=\"layui-btn layui-btn-sm layui-btn-radius\">Delete</a></td>\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("						");

							}
						
      out.write("\n");
      out.write("					</tbody>\n");
      out.write("				</table>\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"layui-tab-item\">\n");
      out.write("				<table class=\"layui-table\">\n");
      out.write("					<colgroup>\n");
      out.write("						<col width=\"150\">\n");
      out.write("						<col width=\"200\">\n");
      out.write("						<col>\n");
      out.write("					</colgroup>\n");
      out.write("					<thead>\n");
      out.write("						<tr>\n");
      out.write("							<th>serial number</th>\n");
      out.write("							<th>Activity name</th>\n");
      out.write("							<th>Organizer</th>\n");
      out.write("							<th>Event participants</th>\n");
      out.write("							<th>Registration start time</th>\n");
      out.write("							<th>Registration close time</th>\n");
      out.write("							<th>The event start time</th>\n");
      out.write("							<th>The event end time</th>\n");
      out.write("							<th>Number of event registrations</th>\n");
      out.write("							<th>revise</th>\n");
      out.write("							<th>Delete</th>\n");
      out.write("						</tr>\n");
      out.write("					</thead>\n");
      out.write("					<tbody>\n");
      out.write("\n");
      out.write("\n");
      out.write("						");

							ActivityDao activityDao = new ActivityDao();
							List<Activity> actList = activityDao.queryAllList();
							for (int i = 0; i < actList.size(); i++) {
								Activity act = actList.get(i);
						
      out.write("\n");
      out.write("						<tr>\n");
      out.write("							<td>");
      out.print(i + 1);
      out.write("</td>\n");
      out.write("							<td>");
      out.print(act.getActName());
      out.write("</td>\n");
      out.write("							<td>");
      out.print(act.getSponsor());
      out.write("</td>\n");
      out.write("							<td>");
      out.print(act.getCoOrganizer());
      out.write("</td>\n");
      out.write("							<td>");
      out.print(act.getSignUpStartDate() == null ? "" : df.format(act.getSignUpStartDate()));
      out.write("</td>\n");
      out.write("							<td>");
      out.print(act.getSignUpEndDate() == null ? "" : df.format(act.getSignUpEndDate()));
      out.write("</td>\n");
      out.write("							<td>");
      out.print(act.getActStartDate() == null ? "" : df.format(act.getActStartDate()));
      out.write("</td>\n");
      out.write("							<td>");
      out.print(act.getActEndDate() == null ? "" : df.format(act.getActEndDate()));
      out.write("</td>\n");
      out.write("							<td align=\"center\"> <a style=\"color:red\"\n");
      out.write("								href=\"signUpDetail.jsp?id=");
      out.print(act.getId());
      out.write('"');
      out.write('>');
      out.print(activityDao.getSingUpNum(act.getId()));
      out.write("</a>\n");
      out.write("							</td>\n");
      out.write("							<td><a\n");
      out.write("								href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/activityEdit.jsp?id=");
      out.print(act.getId());
      out.write("\"\n");
      out.write("								class=\"layui-btn layui-btn-sm layui-btn-radius\">revise</a>\n");
      out.write("							<td><a\n");
      out.write("								href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/deletActivity?actId=");
      out.print(act.getId());
      out.write("\"\n");
      out.write("								class=\"layui-btn layui-btn-sm layui-btn-radius\">Delete</a></td>\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("						");

							}
						
      out.write("\n");
      out.write("					</tbody>\n");
      out.write("				</table>\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			<div class=\"layui-tab-item\">\n");
      out.write("							<table>\n");
      out.write("			\n");
      out.write("							");

									for (int i = 0; i < actList.size(); i++) {
											Activity act = actList.get(i);
								
      out.write("\n");
      out.write("						\n");
      out.write("					<tr>\n");
      out.write("						<td><img src=\"\" width=\"0\">&nbsp;&nbsp;</td>\n");
      out.write("						<td>");
      out.print(act.getActName());
      out.write("<br /> Organizer：");
      out.print(act.getSponsor());
      out.write("<br />\n");
      out.write("							Event participants：");
      out.print(act.getCoOrganizer());
      out.write("<br /> Registration Time ： ");
      out.print(act.getSignUpStartDate() == null ? "" : df.format(act.getSignUpStartDate()));
      out.write("&nbsp;—&nbsp;\n");
      out.write("							");
      out.print(act.getSignUpEndDate() == null ? "" : df.format(act.getSignUpEndDate()));
      out.write("<br />\n");
      out.write("							Event Time ： ");
      out.print(act.getActStartDate() == null ? "" : df.format(act.getActStartDate()));
      out.write("&nbsp;—&nbsp;\n");
      out.write("							");
      out.print(act.getActEndDate() == null ? "" : df.format(act.getActEndDate()));
      out.write("<br />\n");
      out.write("							<br /> <a\n");
      out.write("							href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/activityDetail.jsp?id=");
      out.print(act.getId());
      out.write("\"\n");
      out.write("							class=\"layui-btn layui-btn-sm layui-btn-radius\">Event details</a><br />\n");
      out.write("						<br /></td>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<td colspan=\"2\"></td>\n");
      out.write("					</tr>\n");
      out.write("					");

									}
								
      out.write("\n");
      out.write("				\n");
      out.write("				</table>\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"layui-tab-item\">\n");
      out.write("				");

					String actId = request.getParameter("id");
					Activity act = null;
					if (actId == null) {
						act = new Activity();
					} else {
						ActivityDao newActivityDao = new ActivityDao();
						act = activityDao.queryById(Integer.parseInt(actId));
					}
				
      out.write("\n");
      out.write("\n");
      out.write("				<form class=\"layui-form\" id=\"actForm\"\n");
      out.write("					action=\"");
      out.print(request.getContextPath());
      out.write("/activityEdit\" method=\"post\"\n");
      out.write("					enctype=\"multipart/form-data\">\n");
      out.write("					<input type=\"hidden\" id=\"actId\" name=\"actId\" class=\"layui-input\"\n");
      out.write("						value=\"");
      out.print(act.getId() != null ? act.getId() : "");
      out.write("\" />\n");
      out.write("						\n");
      out.write("\n");
      out.write("					<div class=\"layui-form-item\">\n");
      out.write("						<label class=\"layui-form-label\">Activity name</label>\n");
      out.write("						<div class=\"layui-input-inline\">\n");
      out.write("							<input type=\"text\"\n");
      out.write("								value=\"");
      out.print(act.getActName() != null ? act.getActName() : "");
      out.write("\"\n");
      out.write("								name=\"actName\" id=\"actName\" required lay-verify=\"required\"\n");
      out.write("								placeholder=\"activity name\" autocomplete=\"off\" class=\"layui-input\">\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<div class=\"layui-form-item\">\n");
      out.write("						<label class=\"layui-form-label\">Organizer</label>\n");
      out.write("						<div class=\"layui-input-inline\">\n");
      out.write("							<input type=\"text\"\n");
      out.write("								value=\"");
      out.print(act.getSponsor() != null ? act.getSponsor() : "");
      out.write("\"\n");
      out.write("								name=\"sponsor\" id=\"sponsor\" required lay-verify=\"required\"\n");
      out.write("								placeholder=\"Organizer\" autocomplete=\"off\" class=\"layui-input\">\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"layui-form-item\">\n");
      out.write("						<label class=\"layui-form-label\">Number of people</label>\n");
      out.write("						<div class=\"layui-input-inline\">\n");
      out.write("							<input type=\"text\"\n");
      out.write("								value=\"10\"\n");
      out.write("								name=\"count_tmp\" id=\"count_tmp\" required lay-verify=\"required\"\n");
      out.write("								placeholder=\"Number of people\" autocomplete=\"off\" class=\"layui-input\">\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"layui-form-item\">\n");
      out.write("						<label class=\"layui-form-label\">Parties</label>\n");
      out.write("						<div class=\"layui-input-inline\">\n");
      out.write("							<select name=\"coOrganizer\">\n");
      out.write("								<option value=\"parent\">parent</option>\n");
      out.write("								<option value=\"pets\">pets</option>\n");
      out.write("							</select>\n");
      out.write("							");
      out.write("\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("					<div class=\"layui-form-item\">\n");
      out.write("						<label class=\"layui-form-label\">Registration start time</label>\n");
      out.write("						<div class=\"layui-input-inline\">\n");
      out.write("							<input type=\"date\"\n");
      out.write("								value=\"");
      out.print(act.getSignUpStartDate() != null ? df.format(act.getSignUpStartDate()) : "");
      out.write("\"\n");
      out.write("								name=\"signUpStart\" id=\"signUpStart\" required\n");
      out.write("								lay-verify=\"required\" autocomplete=\"off\" class=\"layui-input\">\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<div class=\"layui-form-item\">\n");
      out.write("						<label class=\"layui-form-label\">Registration close time</label>\n");
      out.write("						<div class=\"layui-input-inline\">\n");
      out.write("							<input type=\"date\"\n");
      out.write("								value=\"");
      out.print(act.getSignUpEndDate() != null ? df.format(act.getSignUpEndDate()) : "");
      out.write("\"\n");
      out.write("								name=\"signUpEnd\" id=\"signUpEnd\" required lay-verify=\"required\"\n");
      out.write("								autocomplete=\"off\" class=\"layui-input\">\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<div class=\"layui-form-item\">\n");
      out.write("						<label class=\"layui-form-label\">The event start time</label>\n");
      out.write("						<div class=\"layui-input-inline\">\n");
      out.write("							<input type=\"date\"\n");
      out.write("								value=\"");
      out.print(act.getActStartDate() != null ? df.format(act.getActStartDate()) : "");
      out.write("\"\n");
      out.write("								name=\"actStart\" id=\"actStart\" required lay-verify=\"required\"\n");
      out.write("								autocomplete=\"off\" class=\"layui-input\">\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<div class=\"layui-form-item\">\n");
      out.write("						<label class=\"layui-form-label\">The event end time</label>\n");
      out.write("						<div class=\"layui-input-inline\">\n");
      out.write("							<input type=\"date\"\n");
      out.write("								value=\"");
      out.print(act.getActEndDate() != null ? df.format(act.getActEndDate()) : "");
      out.write("\"\n");
      out.write("								name=\"actEnd\" id=\"actEnd\" required lay-verify=\"required\"\n");
      out.write("								autocomplete=\"off\" class=\"layui-input\">\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<div class=\"layui-form-item layui-form-text\">\n");
      out.write("						<label class=\"layui-form-label\">Event content</label>\n");
      out.write("						<div class=\"layui-input-block\">\n");
      out.write("							<textarea name=\"actContent\" placeholder=\"please write the content\" class=\"layui-textarea\"\n");
      out.write("								rows=\"5\" form=\"actForm\" name=\"actContent\"></textarea>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"layui-form-item\">\n");
      out.write("						<div class=\"layui-input-block\">\n");
      out.write("							<button class=\"layui-btn\" lay-submit lay-filter=\"formDemo\">Submit</button>\n");
      out.write("							<button type=\"reset\" class=\"layui-btn layui-btn-primary\">Reset</button>\n");
      out.write("\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</form>\n");
      out.write("\n");
      out.write("				<script>\n");
      out.write("					//Demo\n");
      out.write("					layui.use('form', function() {\n");
      out.write("						var form = layui.form;\n");
      out.write("\n");
      out.write("						//监听提交\n");
      out.write("						form.on('submit(formDemo)', function(data) {\n");
      out.write("	\n");
      out.write("							return;\n");
      out.write("						});\n");
      out.write("					});\n");
      out.write("				</script>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<div class=\"layui-tab-item\">\n");
      out.write("\n");
      out.write("				<table class=\"layui-table\">\n");
      out.write("					<colgroup>\n");
      out.write("						<col width=\"150\">\n");
      out.write("						<col width=\"200\">\n");
      out.write("						<col>\n");
      out.write("					</colgroup>\n");
      out.write("					<thead>\n");
      out.write("						<tr>\n");
      out.write("							<th>serial number</th>\n");
      out.write("							<th>Name</th>\n");
      out.write("							<th>User type</th>\n");
      out.write("							<th>Content</th>							\n");
      out.write("						</tr>\n");
      out.write("					</thead>\n");
      out.write("					<tbody>\n");
      out.write("						");

							YuanwangDao dao1 = new YuanwangDao();
							List<Yuanwang> userList1 = dao1.queryAllList();
							for (int i = 0; i < userList1.size(); i++) {
								System.out.print(userList1);
								Yuanwang yuanwang = userList1.get(i);
						
      out.write("\n");
      out.write("						<tr>\n");
      out.write("							<td>");
      out.print(yuanwang.getSn());
      out.write("</td>\n");
      out.write("							<td>");
      out.print(yuanwang.getLeixing());
      out.write("</td>\n");
      out.write("							<td>");
      out.print(yuanwang.getName());
      out.write("</td>\n");
      out.write("							<td>");
      out.print(yuanwang.getContent());
      out.write("</td>							\n");
      out.write("						</tr>\n");
      out.write("						");

							}
						
      out.write("\n");
      out.write("					</tbody>\n");
      out.write("				</table>\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			<div class=\"layui-tab-item\">\n");
      out.write("\n");
      out.write("				<table class=\"layui-table\">\n");
      out.write("					<colgroup>\n");
      out.write("						<col width=\"150\">\n");
      out.write("						<col width=\"200\">\n");
      out.write("						<col>\n");
      out.write("					</colgroup>\n");
      out.write("					<thead>\n");
      out.write("						<tr>\n");
      out.write("							<th>Senior name</th>\n");
      out.write("							<th>The name of the activity</th>\n");
      out.write("							<th>Senior score</th>\n");
      out.write("							<th>Activity evaluation</th>\n");
      out.write("							<th>Evaluators</th>\n");
      out.write("						</tr>\n");
      out.write("					</thead>\n");
      out.write("					<tbody>\n");
      out.write("						");

						DefenDao dao12 = new DefenDao();
						List<Defen> deList = dao12.queryAllList();
						for (int i = 0; i < deList.size(); i++) {
							Defen act21 = deList.get(i);
					
      out.write("<tr>\n");
      out.write("							<td>");
      out.print(act21.getUserid());
      out.write("</td>\n");
      out.write("							<td>");
      out.print(act21.getActname());
      out.write("</td>\n");
      out.write("							<td>");
      out.print(act21.getFenshu());
      out.write("</td>\n");
      out.write("							<td>");
      out.print(act21.getType());
      out.write("</td>\n");
      out.write("							<td>");
      out.print(act21.getDafenren());
      out.write("</td>\n");
      out.write("						</tr>\n");
      out.write("						");

}

      out.write("\n");
      out.write("					</tbody>\n");
      out.write("				</table>\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<script>\n");
      out.write("		//注意：选项卡 依赖 element 模块，否则无法进行功能性操作\n");
      out.write("		layui.use('element', function() {\n");
      out.write("			var element = layui.element;\n");
      out.write("\n");
      out.write("			//…\n");
      out.write("		});\n");
      out.write("	</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
