/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2022-11-28 00:27:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import activityManagement.userModular.dao.UserDao;
import activityManagement.userModular.entity.User;
import java.util.List;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

public final class userEdit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("activityManagement.userModular.entity.User");
    _jspx_imports_classes.add("java.text.DateFormat");
    _jspx_imports_classes.add("activityManagement.userModular.dao.UserDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>User Information Page</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"layui/css/layui.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<script src=\"layui/layui.js\"></script>\n");
      out.write("\n");
      out.write("	");

		String userId = request.getParameter("userId");
		UserDao userDao = new UserDao();
		User user = userDao.queryByUserId(Integer.parseInt(userId));
		DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
	
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<form class=\"layui-form\"\n");
      out.write("		action=\"");
      out.print(request.getContextPath());
      out.write("/userEdit\" method=\"post\">\n");
      out.write("		<input type=\"hidden\" id=\"userId\" name=\"userId\"\n");
      out.write("			value=\"");
      out.print(user.getId());
      out.write("\" />\n");
      out.write("		<div class=\"layui-form-item\">\n");
      out.write("			<label class=\"layui-form-label\">User name</label>\n");
      out.write("			<div class=\"layui-input-inline\">\n");
      out.write("				<input type=\"text\" name=\"userName\" id=\"userName\" required\n");
      out.write("					lay-verify=\"required\" placeholder=\"please input User name\" autocomplete=\"off\"\n");
      out.write("					class=\"layui-input\" value=\"");
      out.print(user.getUserName());
      out.write("\">\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("		<div class=\"layui-form-item\">\n");
      out.write("			<label class=\"layui-form-label\">Password</label>\n");
      out.write("			<div class=\"layui-input-inline\">\n");
      out.write("				<input type=\"password\" name=\"password\" id=\"password\" required\n");
      out.write("					lay-verify=\"required\" placeholder=\"password\" autocomplete=\"off\"\n");
      out.write("					class=\"layui-input\" value=\"");
      out.print(user.getPassword());
      out.write("\">\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div class=\"layui-form-item\">\n");
      out.write("			<label class=\"layui-form-label\">name</label>\n");
      out.write("			<div class=\"layui-input-inline\">\n");
      out.write("				<input type=\"text\" name=\"name\" id=\"name\" required\n");
      out.write("					lay-verify=\"required\" placeholder=\"name\" autocomplete=\"off\"\n");
      out.write("					class=\"layui-input\" value=\"");
      out.print(user.getNickname());
      out.write("\">\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div class=\"layui-form-item\">\n");
      out.write("			<label class=\"layui-form-label\">Sex</label>\n");
      out.write("			<div class=\"layui-input-block\">\n");
      out.write("				<input type=\"radio\" name=\"sex\" id=\"sex\" value=\"M\" title=\"M\"\n");
      out.write("					");
if (user.getSex() != null && user.getSex().equals("M")) {
      out.write("\n");
      out.write("					checked ");
}
      out.write("> <input type=\"radio\" name=\"sex\"\n");
      out.write("					id=\"sex\" value=\"F\" title=\"F\"\n");
      out.write("					");
if (user.getSex() != null && user.getSex().equals("F")) {
      out.write("\n");
      out.write("					checked ");
}
      out.write(">\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div class=\"layui-form-item\">\n");
      out.write("			<label class=\"layui-form-label\">phone number</label>\n");
      out.write("			<div class=\"layui-input-inline\">\n");
      out.write("				<input type=\"number\" name=\"phoneNum\" id=\"phoneNum\" required\n");
      out.write("					lay-verify=\"required\" placeholder=\"phone number\" autocomplete=\"off\"\n");
      out.write("					class=\"layui-input\" value=\"");
      out.print(user.getPhoneNum());
      out.write("\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"layui-form-mid layui-word-aux\"></div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div class=\"layui-form-item\">\n");
      out.write("			<div class=\"layui-input-block\">\n");
      out.write("				<button class=\"layui-btn\" lay-submit lay-filter=\"formDemo\"\n");
      out.write("					type=\"submit\">revise</button>\n");
      out.write("				<button type=\"reset\" class=\"layui-btn layui-btn-primary\"\n");
      out.write("					onclick=\"javascript:history.go(-1);\">return</button>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</form>\n");
      out.write("\n");
      out.write("	<script>\n");
      out.write("//监听\n");
      out.write("layui.use('form', function() {\n");
      out.write("	var form = layui.form;\n");
      out.write("\n");
      out.write("	\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
